### ISSUE TITLE
Fix rows and columns count in ResultSet metadata

### ISSUE THREAD

**Issue by rflprr** [datadotworld/dw-jdbc#22]
ResultSet objects seem to be misreporting the number of rows and columns.

![pasted image at 2017_05_25 09_35 am](https://user-images.githubusercontent.com/1487471/26844852-663be13e-4aba-11e7-8797-d6544314bc20.png)

**Comment by rflprr** [comment]
Upon testing, it turns out that the driver does a good job at reporting the number of columns in `ResultSetMetaData`. The number of rows isn't expected to be in `ResultSetMetaData` anyways. Closing this.

**Comment by shawnsmith** [comment]
In the SQuirreL UI the field pointed to by the red arrow is rendered by the following:
```
private void onRowColSelectedCountChanged(int selectedRowCount, int selectedColumnCount)
{
   s_stringMgr.getString("SelectRowColLabelController.RowColSelectedCountLabel", selectedRowCount, selectedColumnCount);
   _lbl.setText("Rows: " + selectedRowCount + ", Cols: " + selectedColumnCount);
}
```
In other words, it shows the number of columns and rows the user has selected in the result grid.  That's why it shows "Rows: 1, Cols: 0".
